### PR TITLE
ArcadePhoenix.20240817

### PR DESCRIPTION
**Pull request by Sorbas2020**
Better overview for the RAM usage.
Preparation for upcomming analyis.
Separation of ghost codes from older versions of the game development.
Further excavation work.

### CODE REVIEW

**Review by Sorbas2020 — COMMENTED** [review]
I was not able to test the fix.

**Comment by topherCantrell** [comment]
This all looks fantastic. I tweaked the web generator to allow for your "---" separators in the RAM USE. That's a great idea.

**Comment by Sorbas2020** [comment]
Thank you. And have a nice Weekend.

Christopher Cantrell ***@***.***> schrieb am Sa., 17. Aug.
2024, 14:46:

**Comment by Sorbas2020** [comment]
Hi Christopher
i am afraid i did not fully understand the syntax of the pseudo codes for
the web generator. Do you have a documentation for it?
e.g. does {} only work for the call statement?

Greetings Peter


Christopher Cantrell ***@***.***> schrieb am Sa., 17. Aug.
2024, 14:46:

**Comment by topherCantrell** [comment]
I added some documentation here:
https://github.com/topherCantrell/computerarcheology/blob/master/README.md#the-names_in_code-tool

Let me know if that helps, and I can tell you more.

For the most part, the "names_in_code" tool that runs as part of the web
deployment will update all these whether you want it to or not. But there
is some syntax for overriding it.

**Comment by Sorbas2020** [comment]
Yes, that helps. Now i know how to use it.
Thank you.

Christopher Cantrell ***@***.***> schrieb am So., 18. Aug.
2024, 20:43:

> I added some documentation here:
>
> https://github.com/topherCantrell/computerarcheology/blob/master/README.md#the-names_in_code-tool
>
> Let me know if that helps, and I can tell you more.
>
> For the most part, the "names_in_code" tool that runs as part of the web
> deployment will update all these whether you want it to or not. But there
> is some syntax for overriding it.
>

**Comment by Sorbas2020** [comment]
Hi Christopher,

Some of my added pseudo codes are removed. I dont know why.
Did i something wrong?
e.g.
for line:
0149: 21 A3 43     LD   HL,$43A3        ;  {ram.GameAndDemoOrSplash}

the address was at the ram file:
| 43A3      | GameAndDemoOrSplash  | Game and demo:0 Intro splash:2 |

the same happened with line 0377

Please check.

Greetings Peter

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am So., 18. Aug. 2024 um 20:43 Uhr schrieb Christopher Cantrell <
***@***.***>:

> I added some documentation here:
>
> https://github.com/topherCantrell/computerarcheology/blob/master/README.md#the-names_in_code-tool
>
> Let me know if that helps, and I can tell you more.
>
> For the most part, the "names_in_code" tool that runs as part of the web
> deployment will update all these whether you want it to or not. But there
> is some syntax for overriding it.
>

**Comment by topherCantrell** [comment]
By default, the tool will automatically add/remove/change the "{...}"
comments. It doesn't know that "LD HL,$43A3" is a memory address. Trying
telling it explicitly like this:

0149: 21 A3 43 LD HL,$43A3 ; {+}

or

0149: 21 A3 43 LD HL,$43A3 ; {+ram.GameAndDemoOrSplash}

The plus SHOULD make it respect it (and update it if needed)

Let me know!

**Comment by topherCantrell** [comment]
You are the first person, besides me, to use these tools. I really need to
clean them up and document them! Feel free to jump in the madness with me!

**Comment by Sorbas2020** [comment]
Ok. I was just a little bit confused, but now it should work like that.
https://github.com/topherCantrell/computerarcheology/pull/26

Thank you and have a nice evening.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am Mo., 19. Aug. 2024 um 18:52 Uhr schrieb Christopher Cantrell <
***@***.***>:

> By default, the tool will automatically add/remove/change the "{...}"
> comments. It doesn't know that "LD HL,$43A3" is a memory address. Trying
> telling it explicitly like this:
>
> 0149: 21 A3 43 LD HL,$43A3 ; {+}
>
> or
>
> 0149: 21 A3 43 LD HL,$43A3 ; {+ram.GameAndDemoOrSplash}
>
> The plus SHOULD make it respect it (and update it if needed)
>
> Let me know!
>
> On Mon, Aug 19, 2024 at 11:45 AM Sorbas2020 ***@***.***>
> wrote:
>
> > Hi Christopher,
> >
> > Some of my added pseudo codes are removed. I dont know why.
> > Did i something wrong?
> > e.g.
> > for line:
> > 0149: 21 A3 43 LD HL,$43A3 ; {ram.GameAndDemoOrSplash}
> >
> > the address was at the ram file:
> > | 43A3 | GameAndDemoOrSplash | Game and demo:0 Intro splash:2 |
> >
> > the same happened with line 0377
> >
> > Please check.
> >
> > Greetings Peter
> >
> > <
> >
> https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
>
> >
> > Virenfrei.www.avast.com
> > <
> >
> https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
>
> >
> > <#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
> >
> > Am So., 18. Aug. 2024 um 20:43 Uhr schrieb Christopher Cantrell <
> > ***@***.***>:
> >
> > > I added some documentation here:
> > >
> > >
> >
> https://github.com/topherCantrell/computerarcheology/blob/master/README.md#the-names_in_code-tool
> > >
> > > Let me know if that helps, and I can tell you more.
> > >
> > > For the most part, the "names_in_code" tool that runs as part of the
> web
> > > deployment will update all these whether you want it to or not. But
> > there
> > > is some syntax for overriding it.
> > >

**Pull request merged**
